#+---------------------------------------------------------------------------+
#|          01001110 01100101 01110100 01111010 01101111 01100010            |
#|                                                                           |
#|               Netzob : Inferring communication protocols                  |
#+---------------------------------------------------------------------------+
#| Copyright (C) 2011-2017 Georges Bossert and Frédéric Guihéry              |
#| This program is free software: you can redistribute it and/or modify      |
#| it under the terms of the GNU General Public License as published by      |
#| the Free Software Foundation, either version 3 of the License, or         |
#| (at your option) any later version.                                       |
#|                                                                           |
#| This program is distributed in the hope that it will be useful,           |
#| but WITHOUT ANY WARRANTY; without even the implied warranty of            |
#| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the              |
#| GNU General Public License for more details.                              |
#|                                                                           |
#| You should have received a copy of the GNU General Public License         |
#| along with this program. If not, see <http://www.gnu.org/licenses/>.      |
#+---------------------------------------------------------------------------+
#| @url      : http://www.netzob.org                                         |
#| @contact  : contact@netzob.org                                            |
#| @sponsors : Amossys, http://www.amossys.fr                                |
#|             Supélec, http://www.rennes.supelec.fr/ren/rd/cidre/           |
#+---------------------------------------------------------------------------+

#+---------------------------------------------------------------------------+
#| File contributors :                                                       |
#|       - Georges Bossert <gbossert (a) miskin.fr>                          |
#|       - Frédéric Guihéry <frederic.guihery (a) amossys.fr>                |
#+---------------------------------------------------------------------------+

#
# TRAVIS Continuous Integration Definition file
#

# Definition of the environment
env:
  - NETZOB_TEST_NO_PERFORMANCE=yes
language: python
sudo: required
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
addons:
  apt:
    packages:
    - libpcap-dev
    - python3

# Installation process

install:
  - cd netzob
  - python3 -m pip install -r requirements.txt
  - python3 setup.py build
  - python3 setup.py install
  - python3 -m pip install coveralls
  - python3 -m pip install codecov

# Executing unit-tests and measure coverages

script:
  - python3 setup.py test
  - python3 -m coverage run --source=src/netzob setup.py test
after_success:
  - coveralls
  - codecov
